dist: trusty
sudo: required
services: docker
language: scala
scala:
- 2.12.3
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.ivy2"
  - "$HOME/.m2"
  - "$HOME/.sbt"
env:
- GAE_PYTHONPATH=${HOME}/.cache/google_appengine PATH=$PATH:${HOME}/google-cloud-sdk/bin
  PYTHONPATH=${PYTHONPATH}:${GAE_PYTHONPATH} CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
- openssl aes-256-cbc -K $encrypted_9d8d5353ff54_key -iv $encrypted_9d8d5353ff54_iv
  -in credentials.tar.gz.enc -out credentials.tar.gz -d
- python --version
#- if [ ! -d ${HOME}/google-cloud-sdk ]; then curl https://sdk.cloud.google.com | bash;
#  fi
- tar -xzf credentials.tar.gz
- mkdir -p lib
- gcloud auth activate-service-account --key-file client-secret.json
install:
- gcloud config set project neon-pics
#- gcloud -q components update gae-python
#- pip install -r requirements.txt -t lib/
script:
- sbt test
- sbt docker:publishLocal
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    gcloud docker -- push eu.gcr.io/neon-pics/production:latest;
    docker push USER/REPO;
    fi
  - if [ "$TRAVIS_BRANCH" == "develop" ]; then
    gcloud docker -- push eu.gcr.io/neon-pics/stage:latest;
    docker push USER/REPO;
    fi
before_cache:
- find $HOME/.ivy2 -name "ivydata-*.properties" -delete
- find $HOME/.sbt -name "*.lock" -delete
notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
