language: scala
scala:
- 2.12.3
jdk:
- oraclejdk8
script:
- sbt test
before_cache:
- find $HOME/.ivy2 -name "ivydata-*.properties" -delete
- find $HOME/.sbt -name "*.lock" -delete
cache:
  directories:
  - "$HOME/.ivy2"
  - "$HOME/.m2"
  - "$HOME/.sbt"

